name: Test Flask App

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Set up Docker
       uses: docker/setup-buildx-action@v2

     - name: Build Docker image
       run: docker build -t initiative-tracker .

     - name: Run pytest in container
       run: docker run --rm initiative-tracker pytest
